name: Auto Generate Blog

on:
  schedule:
    # 每天早上8点自动运行 (UTC时间，对应北京时间16点)
    - cron: '0 8 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install
          npm install dotenv axios cheerio @supabase/supabase-js rss-parser
      
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
          echo "XAI_API_KEY=${{ secrets.XAI_API_KEY }}" >> .env
      
      - name: Run blog generator
        run: node blog-generator.js
      
      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: blog-generator-logs
          path: blog-generator-*.log
          retention-days: 7 